<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
install.packages("MASS")


The downloaded binary packages are in
	/var/folders/1n/nvr79nb55tz9j4lsbrw6hsf80000gn/T//RtmpcrP17F/downloaded_packages


In [2]:
library(MASS)

Warning message:
“package ‘MASS’ was built under R version 4.0.2”


In [4]:
Cov <- matrix(c(1, 0.5, 0.5, 1), nrow = 2)

mu <- c(0, 0)

simData <- mvrnorm(n= 100, mu, Cov)
simData

[,1]         [,2]       
 [1,]  0.717659949 -0.37324767
 [2,] -0.734772950  1.00278463
 [3,] -0.281747215 -1.07342013
 [4,] -1.412204973 -0.73400380
 [5,] -0.808527648 -1.72310272
 [6,] -0.225018949 -0.22351729
 [7,]  0.044867303  0.68727539
 [8,] -0.294151994  1.34596668
 [9,]  0.131216970 -1.07560569
[10,]  1.312896195  1.22017472
[11,] -0.500209854 -0.25616170
[12,]  0.933135701  0.72152019
[13,] -0.510324370 -0.03956327
[14,]  0.410651345  0.08765694
[15,]  0.527174541  0.75137977
[16,]  0.043970643 -1.24215017
[17,]  0.804343424 -0.61095556
[18,] -1.162987549 -1.52664457
[19,]  0.490904831  1.22802037
[20,] -0.592934918 -0.44255425
[21,]  1.651473072  2.17163277
[22,] -2.071379227 -2.10123036
[23,] -0.383771597  0.07462946
[24,]  0.105090709  0.02651632
[25,] -1.797791257  0.80250848
[26,] -0.133791496  0.12632119
[27,]  2.412525051  2.23907173
[28,] -0.260260932 -1.16021079
[29,]  1.333753748  1.96364775
[30,]  0.008712292 -0.78423162
[31,] ⋮            ⋮          
[32,] -0.19438325   0.21672502
[33,] -1.40490409  -1.55945420
[34,]  1.28792395   0.59440780
[35,]  0.59938466   0.34855478
[36,] -0.44491677   0.43679023
[37,]  1.67234124   0.91514701
[38,]  0.70758623   1.03992611
[39,]  0.49532369   1.20200556
[40,]  1.15160369   0.37648939
[41,]  0.80419401  -0.86054780
[42,] -1.10515422  -0.04352962
[43,] -0.24242137   0.38672188
[44,]  0.08075124   0.92408474
[45,] -0.44231049  -0.31195576
[46,] -2.10575188  -0.71881643
[47,] -0.42844551  -2.38630569
[48,] -1.03809649  -1.56321580
[49,] -2.64154335  -1.92186896
[50,] -1.44206222  -0.38471964
[51,]  0.03056172   0.67199315
[52,]  1.09350650  -0.18477451
[53,] -1.52421303  -0.01137245
[54,] -1.78341885  -2.47586864
[55,] -1.04712646  -0.90935574
[56,] -1.06821079  -1.25754055
[57,]  1.29199382   0.48610447
[58,] -2.20842878  -0.86841737
[59,] -0.68402324  -0.66868762
[60,]  1.89942343  -0.71974482
[61,] -1.77230745  -1.33390836

In [8]:
A = matrix(c(4,1,1,1), ncol=2)
A

[,1] [,2]
[1,] 4    1   
[2,] 1    1

In [9]:
cor(A)

Warning message in cor(A):
“the standard deviation is zero”


[,1] [,2]
[1,]  1   NA  
[2,] NA    1