<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Basics" data-toc-modified-id="Basics-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Basics</a></span><ul class="toc-item"><li><span><a href="#Objectives" data-toc-modified-id="Objectives-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Objectives</a></span></li></ul></li><li><span><a href="#Matrix-Algebra-Notation" data-toc-modified-id="Matrix-Algebra-Notation-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Matrix Algebra Notation</a></span><ul class="toc-item"><li><span><a href="#Creating-a-Matrix" data-toc-modified-id="Creating-a-Matrix-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Creating a Matrix</a></span></li><li><span><a href="#Matrix-Dimensions" data-toc-modified-id="Matrix-Dimensions-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Matrix Dimensions</a></span><ul class="toc-item"><li><span><a href="#Querying-Dimensions" data-toc-modified-id="Querying-Dimensions-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>Querying Dimensions</a></span></li><li><span><a href="#Vectors" data-toc-modified-id="Vectors-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>Vectors</a></span></li><li><span><a href="#Tranpose" data-toc-modified-id="Tranpose-2.2.3"><span class="toc-item-num">2.2.3&nbsp;&nbsp;</span>Tranpose</a></span></li></ul></li><li><span><a href="#Matrix-Arithmetic" data-toc-modified-id="Matrix-Arithmetic-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Matrix Arithmetic</a></span><ul class="toc-item"><li><span><a href="#Matrix-Multiplication" data-toc-modified-id="Matrix-Multiplication-2.3.1"><span class="toc-item-num">2.3.1&nbsp;&nbsp;</span>Matrix Multiplication</a></span></li><li><span><a href="#Elementwise-Multiplication" data-toc-modified-id="Elementwise-Multiplication-2.3.2"><span class="toc-item-num">2.3.2&nbsp;&nbsp;</span>Elementwise Multiplication</a></span></li><li><span><a href="#Determinant" data-toc-modified-id="Determinant-2.3.3"><span class="toc-item-num">2.3.3&nbsp;&nbsp;</span>Determinant</a></span></li><li><span><a href="#Trace-of-Matrix" data-toc-modified-id="Trace-of-Matrix-2.3.4"><span class="toc-item-num">2.3.4&nbsp;&nbsp;</span>Trace of Matrix</a></span></li><li><span><a href="#Inverse-of-Matrix" data-toc-modified-id="Inverse-of-Matrix-2.3.5"><span class="toc-item-num">2.3.5&nbsp;&nbsp;</span>Inverse of Matrix</a></span></li></ul></li></ul></li><li><span><a href="#Covariance,-Correlation,-and-Distances" data-toc-modified-id="Covariance,-Correlation,-and-Distances-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Covariance, Correlation, and Distances</a></span><ul class="toc-item"><li><span><a href="#Covariance" data-toc-modified-id="Covariance-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Covariance</a></span><ul class="toc-item"><li><span><a href="#Just-Variance" data-toc-modified-id="Just-Variance-3.1.1"><span class="toc-item-num">3.1.1&nbsp;&nbsp;</span>Just Variance</a></span></li><li><span><a href="#Non-Directionality" data-toc-modified-id="Non-Directionality-3.1.2"><span class="toc-item-num">3.1.2&nbsp;&nbsp;</span>Non-Directionality</a></span></li><li><span><a href="#Covariance-Between-Multiple-Variables" data-toc-modified-id="Covariance-Between-Multiple-Variables-3.1.3"><span class="toc-item-num">3.1.3&nbsp;&nbsp;</span>Covariance Between Multiple Variables</a></span></li></ul></li><li><span><a href="#Correlation" data-toc-modified-id="Correlation-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Correlation</a></span><ul class="toc-item"><li><span><a href="#Convert-Covariance-Matrix-to-Correlation-Matrix" data-toc-modified-id="Convert-Covariance-Matrix-to-Correlation-Matrix-3.2.1"><span class="toc-item-num">3.2.1&nbsp;&nbsp;</span>Convert Covariance Matrix to Correlation Matrix</a></span></li></ul></li><li><span><a href="#Distances" data-toc-modified-id="Distances-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Distances</a></span></li></ul></li></ul></div>

# 1.0 Intro to Multivariate Analysis

## Basics
- Multivariate analysis:
	- Analysis with multiple variables 🤯
	- Includes methods both for describing and exploring multivariate data and exploring the data or making formal inferences about them
- The main goal is exploring data
- Terminology
	- Rows: observations
	- Columns: variables

### Objectives
- Data dimension reduction and simplification
	- Like Principal Components Analysis (PCA)
		- Reduces the number of variables that need to be considered to the *principal components*
		- Principal components
			- Linear combinations of the original variables
- Multivariate visualizations
    - Multidimensional Scaling
        - Visual representation of distances or dissimilarities between sets of objects
        - Objects that are more similar (shorter distances) are closer together than objects that are less similar (longer distances)
- Sorting and Grouping
    - Cluster analysis
        - Concerned with the identification of groups of similar objects

## Matrix Algebra Notation

- Matrix
    - An array of numbers with rows and columns considered as a single entity
    - m x n matrix = m rows and n columns
- Square matrix
    - m = n
    - Only a single column

### Creating a Matrix

Create a 2 x 3 matrix in R
- Matrix denoted "A"

In [3]:
A <- matrix(c(2, -1, 3, 0, 1, 4), ncol=3)
A

[,1] [,2] [,3]
[1,]  2   3    1   
[2,] -1   0    4

Matrix can also be defined row by row
- Notice change in number order in parameter

In [4]:
A <- matrix(c(2, 3, 1, -1, 0, 4), ncol=3, byrow = T)
A

[,1] [,2] [,3]
[1,]  2   3    1   
[2,] -1   0    4

### Matrix Dimensions

#### Querying Dimensions

- Function `dim()` 
    - 2-dimension vector carrying the number of rows and columns
    - Here we see we have 2 rows and 3 columns

In [5]:
dim(A)

[1] 2 3

The number of rows and columns can be individually invoked
- Rows: `nrow`
- Columns: `ncol`

In [6]:
ncol(A)

[1] 3

In [7]:
nrow(A)

[1] 2

#### Vectors

By setting `ncol = 1` we create a column vector

In [8]:
V = matrix(c(-1,1,0), ncol=1)
V

[,1]
[1,] -1  
[2,]  1  
[3,]  0

The same with rows and `nrow=1`

In [9]:
rV = matrix(c(-1,1,0), nrow=1)
rV

[,1] [,2] [,3]
[1,] -1   1    0

#### Tranpose
- The transpose of a matrix is the interchanging of its rows and columns
- In R we can perform a transposition with `t()`

In [10]:
t(A)

[,1] [,2]
[1,] 2    -1  
[2,] 3     0  
[3,] 1     4

### Matrix Arithmetic

#### Matrix Multiplication
- We can perform a multiplaction ncol of A equals nrow of V
- Operator: `%*%`

Example:
- A is an i x j matrix (above)
- V is a j x k matrix (also above)
- $A_{i * j} * V_{j * k} = AV_{i * k}$
- The matrix product AV results in a matrix with i rows and k columns
- Multiply each row item of A by each column in V, sum those products in a row
    - This leaves you with a 2x1 matrix
    - First row: 2(-1) + 3(1) + 1(0) = 1
    - Second row: -1(-1) + 0(1) + 4(0) = 1

**Extra explanation provided by my professor (Dr. Alireza Sheikh-Zadeh):**

>The whole point of matrix multiplication is to construct measure linear (equation) summations. For example,

>y = 2x_1 + 3x_2 + x_3

>Suppose x_1, x_2, and x_3 can be 10, 10, 15, respectively. If I want to measure y I can use matrix multiplication.

>If I say coefficients is a matrix A = [2, 3, 1], A is a 1x3 matrix. And X = transpose[10, 10, 15] is a 3x1 matrix. For finding y I need to do matrix multiplication of A%*%X, which will be a 1x1 matrix (or a scaler).

>Now, think that your X matrix is 3x2, or in other word x_1, x_2, and x_3, each can have two values, then Y also should be two values, a matrix of 1x2. This only happens if you do matrix multiplication.



In [21]:
Result1 = A %*% V
Result1

[,1]
[1,] 1   
[2,] 1

#### Elementwise Multiplication
- Element by element
- Operator: `*`
- Both matrices must have the same dimensions
    - nrow=nrow and ncol=ncol

In [14]:
# Create a new matrix to practice elementwise multiplication
B <- matrix(c(1, -1, 1, -1, 1, -2), ncol=3)
B

[,1] [,2] [,3]
[1,]  1    1    1  
[2,] -1   -1   -2

In [15]:
# Do the multiplication
Result2 = A * B
Result2

[,1] [,2] [,3]
[1,] 2    3     1  
[2,] 1    0    -8

#### Determinant
- A unique number associated with a sqaure matrix
    - Remember square matrix is ncol=nrow
- Found with `det()`
- If determinant is 0, we cannot find the inverse
- We don't know what it means yet, but it's provocative (complicated)

In [16]:
# Create matrix C
C <- matrix(c(1, 2, 3, 4), ncol=2, byrow = T)
C

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [17]:
# Establish and print determinant 
detC = det(C)
detC

[1] -2

#### Trace of Matrix
- A trace is the sum of the matrix's diagonal terms
- Only defined for a square matrix
- Found with `sum()`

In [18]:
sum(diag(C))

[1] 5

#### Inverse of Matrix
- The mathematical inverse of the matrix 
- Take our matrix C
    - Inverse is $C^{-1}$
    - $C * C^{-1} = I$
    - I is the identity of the matrix
- Use `solve()` to find inverse

In [19]:
Cinv = solve(C)
Cinv

[,1] [,2]
[1,] -2.0  1.0
[2,]  1.5 -0.5

In [22]:
# Confirm the inverse

# Round to 10 decimals because of weird binary computer math
round(C %*% Cinv, 10)

[,1] [,2]
[1,] 1    0   
[2,] 0    1

## Covariance, Correlation, and Distances
- Patterns in data can be implied by relationships between the columns (variables) or the relativeness "closeness" of the rows
- Multivariate analysis allows us to examine these as well as the different variable values given to us by univariate methods

### Covariance
- The covariance of two random variables is a measure of their linear dependence 
- The population covariance of two random variables $X_i$ and $X_j$ is a measure of the expected joint variability of the two random variables
    
    This joint variability is defined by:
    
    $Cov(X_i,X_j) = σ_{ij} = E((X_i - μ_o)(X_j - μ_j))$
    
    Where $μ_i = E(X_i)$ and $μ_j = E(X_j)$
- Use `cov()` to find covariance

In [23]:
# Read in example data
measure <-read.csv("https://rb.gy/h2nkrx")
head(measure)

Chest Waist Hips Gender
1 34    30    32   1     
2 37    32    37   1     
3 38    30    36   1     
4 36    33    39   1     
5 38    29    33   1     
6 43    32    38   1

In [28]:
# Control number of digits/decimals
# Apparently doesn't work in notebooks
options(digits = 3)

In [29]:
# Find covariance of chest and waist measurements
cov(measure$Chest, measure$Waist)

[1] 6.37

#### Just Variance
If i - j then the covariance of the variable with itself is just the variance
- There is therefore no need to define variances and covariances independently 

In [30]:
cov(measure$Chest, measure$Chest)

[1] 6.63

In [31]:
var(measure$Chest)

[1] 6.63

#### Non-Directionality
If $X_i$ and $X_j$ are independent, then covariance is necessarily zero
- Larger values of covariance imply a greater degree of linear dependence
- Covariance is non-directional 
    - $Cov(X_i, X_j) = Cov(X_j, X_i)$

In [32]:
cov(measure$Chest, measure$Waist)

[1] 6.37

In [33]:
# Regardless of which variable is first we get the same result
cov(measure$Waist, measure$Chest)

[1] 6.37

#### Covariance Between Multiple Variables
- We use a symmetric square matrix
- The notation for the covariance matrix is Σ

In [37]:
cov(measure[,1:2])

Chest Waist
Chest 6.63   6.37
Waist 6.37  12.53

Find the column means with `colMeans`

In [35]:
colMeans(measure[,1:2])

Chest Waist 
   37    28

In [36]:
cov(measure[,1:3])

Chest Waist Hips
Chest 6.63   6.37 3.00
Waist 6.37  12.53 3.58
Hips  3.00   3.58 5.94

### Correlation
- The covariance can be unintuitive because it is dependent on the scale of the variables used
- Correlation 'standardizes' the covariance by dividing it by the product of the variable standard deviations
    - Called the correlation coefficient
- Use `cor()` to find the correlation

$Corr(X_i,X_j) = ρ_{ij} = \frac{Cov(X_i,X_j)}{σ_iσ_j}$

In [38]:
cor(measure$Chest, measure$Waist)

[1] 0.699

Manually calculated from covariance:

In [39]:
cov(measure$Chest, measure$Waist)/(sd(measure$Chest)*sd(measure$Waist))

[1] 0.699

Creating square matrix to show multiple correlations
- Notation for a covariance matrix is R

In [40]:
corr = cor(measure[,1:3])
corr

Chest Waist Hips 
Chest 1.000 0.699 0.478
Waist 0.699 1.000 0.415
Hips  0.478 0.415 1.000

#### Convert Covariance Matrix to Correlation Matrix
- Cannot be done in reverse
- Use `cov2cor`

In [43]:
cov = cov(measure[,1:3])
cov2cor(cov)

Chest Waist Hips 
Chest 1.000 0.699 0.478
Waist 0.699 1.000 0.415
Hips  0.478 0.415 1.000

### Distances
- Finding the 'distance' between units (rows) in the dataset is important
    - Especially in multidimensional scaling and cluster analysis
- Given two units i and j, the Euclidean distance is how we measure...distance
- [I can go the distance](https://www.youtube.com/watch?v=vRAu4kvpmEs)
- Use `dist()` in R 

The **Eucledian Distance**

(If you're reading the PDF, peep the .md to see me flex my mediocre LaTeX) 

$d_{ij} = \sqrt{\sum\limits_{k=1}^q(X_{ik} - X_{jk})^2}$


The Euclidean distance between the first two rows/observations/units:

In [44]:
d = dist(measure[1:2, 1:3])
d

     1
2 6.16

Euclidean distances depend on measurement scales
- We need to standardize the data first
- Use `scale()`

In [46]:
# Scale the data
measure.s = scale(measure[, 1:3])

# Get the distance
d.s = dist(measure.s[1:2, ])
d.s

     1
2 2.43

The pairwise scaled Euclidean distances between the first 10 units:

In [48]:
distances.s = dist(measure.s[1:10,])

# Round the distances
round((distances.s),2)

      1    2    3    4    5    6    7    8    9
2  2.43                                        
3  2.26 0.80                                   
4  3.09 0.95 1.68                              
5  1.63 1.89 1.26 2.82                         
6  4.31 2.37 2.18 2.76 2.95                    
7  4.79 2.38 2.72 1.98 3.94 2.03               
8  3.63 1.41 1.64 1.22 2.88 2.18 1.41          
9  3.10 1.29 0.88 1.95 1.84 1.36 2.22 1.46     
10 3.99 1.76 1.79 1.96 2.85 0.88 1.32 1.36 1.07